# Generated by Django 5.1.4 on 2025-01-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_module', '0002_user_id_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
